---
- name: Install Java 1.8
  yum: 
    name: java-1.8.0-openjdk 
    state: present

- name: Check unzip is installed - if not install
  yum:
    name: unzip
    state: present

- name: add group "jboss"
  group: 
    name: jboss

- name: add user "jboss"
  user: 
    name: jboss 
    group: jboss 
    home: /usr/share/jboss 
    createhome: no

#  become: True
#  become_method: sudo

- name: Download JBoss version {{ jboss_version }} - check
  get_url: 
    url: "http://{{ software_repo_ip }}/jboss/jboss-eap-{{ jboss_version }}.zip" 
    dest: "/opt/jboss-eap-{{ jboss_version }}.zip"

- name: Extract archive
  unarchive:
    src: "/opt/jboss-eap-{{ jboss_version }}.zip"
    dest: /usr/share
    remote_src: yes
    owner: jboss
    group: jboss
    creates: "/usr/share/jboss-eap-{{ jboss_version_unzip }}"


- name: Symlink install directory
  file: 
    src: "/usr/share/jboss-eap-{{ jboss_version_unzip }}" 
    path: /usr/share/jboss-as
    state: link

- name: Change ownership of JBoss installation
  file: 
    path: /usr/share/jboss/ 
    owner: jboss 
    group: jboss  
    state: directory  
    recurse: yes
  changed_when: false

- name: Make the JBoss Configuration Directory
  file:
    path: /etc/jboss-as
    owner: jboss
    group: jboss
    mode: 0755
    state: directory

- name: Install configuration file
  template:
    src: templates/jboss-as.conf.j2
    dest: /etc/jboss-as/jboss-as.conf
    owner: jboss
    group: jboss
    mode: 0644

- name: Copy the JBoss Service into place
  copy:
    src: /usr/share/jboss/bin/init.d/jboss-as-standalone.sh
    dest: /etc/init.d
    remote_src: true
    mode: 0750
     
#- name: Configure JBoss server
#  template: 
#    src:  templates/server.xml.j2 
#    dest: /usr/share/tomcat/conf/server.xml
#  notify: restart tomcat

#- name: Configure Tomcat users
#  template: 
#    src: templates/tomcat-users.xml.j2 
#    dest: /usr/share/tomcat/conf/tomcat-users.xml
#  notify: restart tomcat

#- name: Install the Tomcat Service
#  template:
#    src: templates/tomcat.service.j2 
#    dest: /etc/systemd/system/tomcat.service
#  notify: restart tomcat

#- name: Install Tomcat init script
#  copy: src={{filesdir}}/tomcat-8.5.9/tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755
 
#- name: Register Tomcat
#  service: name=tomcat enabled=yes

#- name: Start JBoss
#  service: 
#    name: jboss 
#    state: started 
#    enabled: yes

- name: deploy iptables rules
  template: 
    src: iptables-save 
    dest: /etc/sysconfig/iptables
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"
  notify: restart iptables

- name: insert firewalld rule for tomcat http port
  firewalld: 
    port: "{{ http_port }}/tcp" 
    permanent: true 
    state: enabled 
    immediate: yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: insert firewalld rule for tomcat https port
  firewalld: 
    port: "{{ https_port }}/tcp" 
    permanent: true 
    state: enabled 
    immediate: yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: wait for JBoss to start
  wait_for: 
    port: "{{http_port}}"
